#TODO: Add actual secrets, this files is just a placeholder
apiVersion: v1
kind: Secret
metadata:
  name: universal-secrets
  namespace: universal-exchange
type: Opaque
data:
  # Base64 encoded secrets
  # Use: echo -n "your-actual-api-key" | base64
  UNIVERSAL_API_KEY: eW91ci11bml2ZXJzYWwtYXBpLWtleQ==  # your-universal-api-key
  
  # External Database credentials (AWS RDS, Google Cloud SQL, etc.)
  # Replace with actual external database connection string
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGRiLWNsdXN0ZXIucmVnaW9uLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvdW5pdmVyc2FsX2V4Y2hhbmdl
  
  # External Redis credentials (AWS ElastiCache, Google Memorystore, etc.)
  # Base64 encoded: redis://username:password@redis-cluster.region.cache.amazonaws.com:6379
  REDIS_URL: cmVkaXM6Ly91c2VybmFtZTpwYXNzd29yZEByZWRpcy1jbHVzdGVyLnJlZ2lvbi5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk= 